# Generated by Django 6.1 on 2026-09-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.IntegerField(default=0),
        ),
    ]
