# Generated by Django 6.1 on 2026-09-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_staffapplication_application_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='credential_document',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='degree_document',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='insurance_document',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='license_document',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
