# Generated by Django 6.1 on 2026-09-12 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_staffapplication_credential_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='credential_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/credentials/'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='degree_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/degrees/'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/insurance/'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/licenses/'),
        ),
    ]
