from django.core.management.base import BaseCommand
from nutrition_plans.models import Food


FOODS = [
    {
        "name": "Egg",
        "category": "Protein",
        "serving": "1 egg",
        "serving_amount": 1,
        "serving_unit": "egg",
        "calories": 72,
        "protein": 6.3,
        "carbohydrates": 0.4,
        "fat": 4.8,
        "fiber": 0,
    },
    {
        "name": "Injera",
        "category": "Grain",
        "serving": "1 piece",
        "serving_amount": 1,
        "serving_unit": "piece",
        "calories": 166,
        "protein": 5.0,
        "carbohydrates": 33.0,
        "fat": 1.0,
        "fiber": 3.0,
    },
    {
        "name": "Shiro",
        "category": "Legume",
        "serving": "1 cup",
        "serving_amount": 1,
        "serving_unit": "cup",
        "calories": 250,
        "protein": 12.0,
        "carbohydrates": 35.0,
        "fat": 7.0,
        "fiber": 8.0,
    },
    {
        "name": "Doro Wat",
        "category": "Protein",
        "serving": "1 serving",
        "serving_amount": 1,
        "serving_unit": "serving",
        "calories": 350,
        "protein": 25.0,
        "carbohydrates": 12.0,
        "fat": 22.0,
        "fiber": 3.0,
    },
    {
        "name": "Tibs",
        "category": "Protein",
        "serving": "1 serving",
        "serving_amount": 1,
        "serving_unit": "serving",
        "calories": 300,
        "protein": 28.0,
        "carbohydrates": 8.0,
        "fat": 18.0,
        "fiber": 2.0,
    },
    {
        "name": "Chicken Breast",
        "category": "Protein",
        "serving": "100 g",
        "serving_amount": 100,
        "serving_unit": "g",
        "calories": 165,
        "protein": 31.0,
        "carbohydrates": 0,
        "fat": 3.6,
        "fiber": 0,
    },
    {
        "name": "Fish",
        "category": "Protein",
        "serving": "100 g",
        "serving_amount": 100,
        "serving_unit": "g",
        "calories": 206,
        "protein": 22.0,
        "carbohydrates": 0,
        "fat": 12.0,
        "fiber": 0,
    },
    {
        "name": "Lentils",
        "category": "Legume",
        "serving": "1 cup",
        "serving_amount": 1,
        "serving_unit": "cup",
        "calories": 230,
        "protein": 18.0,
        "carbohydrates": 40.0,
        "fat": 0.8,
        "fiber": 16.0,
    },
    {
        "name": "Brown Rice",
        "category": "Grain",
        "serving": "1 cup",
        "serving_amount": 1,
        "serving_unit": "cup",
        "calories": 216,
        "protein": 5.0,
        "carbohydrates": 45.0,
        "fat": 1.8,
        "fiber": 3.5,
    },
    {
        "name": "White Rice",
        "category": "Grain",
        "serving": "1 cup",
        "serving_amount": 1,
        "serving_unit": "cup",
        "calories": 205,
        "protein": 4.3,
        "carbohydrates": 44.5,
        "fat": 0.4,
        "fiber": 0.6,
    },
    {
        "name": "Oatmeal",
        "category": "Grain",
        "serving": "1 cup",
        "serving_amount": 1,
        "serving_unit": "cup",
        "calories": 154,
        "protein": 5.4,
        "carbohydrates": 27.0,
        "fat": 2.6,
        "fiber": 4.0,
    },
    {
        "name": "Greek Yogurt",
        "category": "Dairy",
        "serving": "1 cup",
        "serving_amount": 1,
        "serving_unit": "cup",
        "calories": 130,
        "protein": 11.0,
        "carbohydrates": 9.0,
        "fat": 5.0,
        "fiber": 0,
    },
    {
        "name": "Milk",
        "category": "Dairy",
        "serving": "1 cup",
        "serving_amount": 1,
        "serving_unit": "cup",
        "calories": 122,
        "protein": 8.0,
        "carbohydrates": 12.0,
        "fat": 5.0,
        "fiber": 0,
    },
    {
        "name": "Avocado",
        "category": "Fruit",
        "serving": "100 g",
        "serving_amount": 100,
        "serving_unit": "g",
        "calories": 160,
        "protein": 2.0,
        "carbohydrates": 8.5,
        "fat": 14.7,
        "fiber": 6.7,
    },
    {
        "name": "Banana",
        "category": "Fruit",
        "serving": "1 banana",
        "serving_amount": 1,
        "serving_unit": "banana",
        "calories": 105,
        "protein": 1.3,
        "carbohydrates": 27.0,
        "fat": 0.4,
        "fiber": 3.1,
    },
    {
        "name": "Apple",
        "category": "Fruit",
        "serving": "1 apple",
        "serving_amount": 1,
        "serving_unit": "apple",
        "calories": 95,
        "protein": 0.5,
        "carbohydrates": 25.0,
        "fat": 0.3,
        "fiber": 4.4,
    },
    {
        "name": "Spinach",
        "category": "Vegetable",
        "serving": "1 cup",
        "serving_amount": 1,
        "serving_unit": "cup",
        "calories": 7,
        "protein": 0.9,
        "carbohydrates": 1.1,
        "fat": 0.1,
        "fiber": 0.7,
    },
    {
        "name": "Tomato",
        "category": "Vegetable",
        "serving": "1 tomato",
        "serving_amount": 1,
        "serving_unit": "tomato",
        "calories": 22,
        "protein": 1.1,
        "carbohydrates": 4.8,
        "fat": 0.2,
        "fiber": 1.5,
    },
    {
        "name": "Carrot",
        "category": "Vegetable",
        "serving": "1 carrot",
        "serving_amount": 1,
        "serving_unit": "carrot",
        "calories": 25,
        "protein": 0.6,
        "carbohydrates": 6.0,
        "fat": 0.1,
        "fiber": 1.7,
    },
    {
        "name": "Almonds",
        "category": "Nuts",
        "serving": "28 g",
        "serving_amount": 28,
        "serving_unit": "g",
        "calories": 164,
        "protein": 6.0,
        "carbohydrates": 6.1,
        "fat": 14.2,
        "fiber": 3.5,
    },
]


class Command(BaseCommand):
    help = "Seed the food database"

    def handle(self, *args, **kwargs):
        created = 0

        for food_data in FOODS:
            food, was_created = Food.objects.get_or_create(
                name=food_data["name"],
                defaults=food_data,
            )

            if was_created:
                created += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {created} new food(s). {len(FOODS)} total in seed list."
            )
        )