# Generated by Django 6.1 on 2026-09-04 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Protein', 'Protein'), ('Grains', 'Grains'), ('Legumes', 'Legumes'), ('Dairy', 'Dairy'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Nuts', 'Nuts'), ('Other', 'Other')], default='Other', max_length=50)),
                ('unit_based', models.BooleanField(default=False)),
                ('unit_name', models.CharField(default='g', max_length=50)),
                ('grams_per_unit', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealLibrary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Snack', 'Snack'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealLibraryItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_items', to='nutrition_plans.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition_plans.meallibrary')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=255)),
                ('goal', models.CharField(choices=[('Weight Management', 'Weight Management'), ('Healthy Weight Gain', 'Healthy Weight Gain'), ('Balanced Nutrition', 'Balanced Nutrition'), ('Diabetes Management', 'Diabetes Management'), ('Heart Health', 'Heart Health'), ('Improved Energy', 'Improved Energy'), ('General Wellness', 'General Wellness')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to=settings.AUTH_USER_MODEL)),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_nutrition_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanMeal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Snack', 'Snack'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('source', models.CharField(choices=[('library', 'Library'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('nutrition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition_plans.nutritionplan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMealItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='nutrition_plans.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition_plans.planmeal')),
            ],
            options={
                'unique_together': {('meal', 'food')},
            },
        ),
    ]
