# Generated by Django 6.1 on 2026-09-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meallibrary',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='food',
            old_name='carbs',
            new_name='carbohydrates',
        ),
        migrations.RenameField(
            model_name='meallibrary',
            old_name='created_by',
            new_name='nutritionist',
        ),
        migrations.RemoveField(
            model_name='food',
            name='grams_per_unit',
        ),
        migrations.RemoveField(
            model_name='food',
            name='unit_based',
        ),
        migrations.RemoveField(
            model_name='food',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='meallibrary',
            name='is_active',
        ),
        migrations.AddField(
            model_name='food',
            name='serving',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='serving_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='serving_unit',
            field=models.CharField(default='g', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meallibrary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meallibrary',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Dinner', 'Dinner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meallibraryitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_library_items', to='nutrition_plans.food'),
        ),
        migrations.AlterField(
            model_name='meallibraryitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meallibraryitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='nutrition_plans.meallibrary'),
        ),
        migrations.AlterUniqueTogether(
            name='meallibraryitem',
            unique_together={('meal', 'food')},
        ),
    ]
