# Generated by Django 6.1 on 2026-09-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_plans', '0002_alter_meallibrary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
