# Generated by Django 6.1 on 2026-09-06 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_plans', '0003_alter_food_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meallibrary',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='meallibraryitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='food',
            name='serving',
        ),
        migrations.RemoveField(
            model_name='food',
            name='serving_amount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='serving_unit',
        ),
        migrations.RemoveField(
            model_name='meallibrary',
            name='nutritionist',
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='food',
            name='grams_per_unit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='food',
            name='unit_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='unit_name',
            field=models.CharField(default='g', max_length=50),
        ),
        migrations.AddField(
            model_name='meallibrary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_library', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meallibrary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Protein', 'Protein'), ('Grains', 'Grains'), ('Legumes', 'Legumes'), ('Dairy', 'Dairy'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Nuts', 'Nuts'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='meallibrary',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meallibrary',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Snack', 'Snack'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meallibraryitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_items', to='nutrition_plans.food'),
        ),
        migrations.AlterField(
            model_name='meallibraryitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meallibraryitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition_plans.meallibrary'),
        ),
    ]
