# Generated by Django 6.1 on 2026-09-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_plans', '0005_alter_meallibrary_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='preparation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='serving_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
