# Generated by Django 6.1 on 2026-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_plans', '0006_food_preparation_food_serving_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('name', 'preparation'), name='unique_food_preparation'),
        ),
    ]
