# Generated by Django 6.1 on 2026-09-02 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('catering', 'Catering Service'), ('food_manufacturer', 'Food Manufacturer'), ('grocery', 'Grocery / Food Store'), ('bakery', 'Bakery'), ('other', 'Other')], max_length=50)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_document', models.FileField(upload_to='vendors/licenses/')),
                ('food_safety_certificate', models.FileField(upload_to='vendors/food_safety/')),
                ('owner_id_document', models.FileField(upload_to='vendors/owner_ids/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ai_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ai_result', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('business_type', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vendors/products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendorprofile')),
            ],
        ),
    ]
