# Generated by Django 4.2.29 on 2026-08-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='fasting_preference',
            field=models.CharField(blank=True, choices=[('none', 'No Fasting'), ('16_8', '16:8'), ('18_6', '18:6'), ('20_4', '20:4'), ('omad', 'OMAD (One Meal a Day)'), ('alternate_day', 'Alternate Day Fasting'), ('other', 'Other')], help_text='From nutrition screen', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='meals_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='From lifestyle screen', null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='primary_goal',
            field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('maintain_weight', 'Maintain Weight'), ('build_muscle', 'Build Muscle'), ('improve_health', 'Improve Health'), ('manage_condition', 'Manage a Health Condition')], help_text='From health-goals screen', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('extra_active', 'Extra Active')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]