# Generated by Django 4.2.29 on 2026-08-31 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0002_healthprofile_fasting_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=150)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20)),
                ('date', models.DateField()),
                ('portion_label', models.CharField(blank=True, max_length=100)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=7)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='health.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'logged_at'],
            },
        ),
    ]
