# Generated by Django 4.2.29 on 2026-08-31 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_food_foodentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselog',
            options={'ordering': ['-date', '-logged_at']},
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=10),
        ),
    ]
