# Generated by Django 4.2.29 on 2026-08-31 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_exerciselog_options_exerciselog_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightlog',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='weightlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddConstraint(
            model_name='weightlog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_weight_log_per_user_per_date'),
        ),
    ]
