# Generated by Django 4.2.29 on 2026-08-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_weightlog_options_weightlog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='calorie_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='carbs_target_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='fat_target_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='protein_target_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='water_glass_size_ml',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='water_target_glasses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
