# Generated by Django 6.1 on 2026-09-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_aisuggestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofile',
            name='primary_goal',
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('mostly-sitting', 'Mostly Sitting'), ('light', 'Light Activity'), ('active', 'Active'), ('very-active', 'Very Active')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='fasting_preference',
            field=models.CharField(blank=True, choices=[('none', 'No Fasting'), ('sometimes', 'Sometimes'), ('regularly', 'Regularly'), ('religious', 'Religious Fasting')], help_text='From nutrition screen', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('private', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='meals_per_day',
            field=models.CharField(blank=True, help_text="From lifestyle screen. Free text on mobile (e.g. '3', '4-5'), not guaranteed numeric.", max_length=10, null=True),
        ),
    ]
