# Generated by Django 6.1 on 2026-09-10 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_remove_healthprofile_primary_goal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterlog',
            options={'ordering': ['-date', '-logged_at']},
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
