# Generated by Django 6.1 on 2026-09-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_alter_waterlog_options_food_image_waterlog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='serving_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
